<?php namespace App\Http\Models;

use Illuminate\Database\Eloquent\Model;

class AirHspDB extends Model {
    protected $primaryKey = 'id';
    public $incrementing = true;
    //public $timestamps = false; 
    protected $table = 'air_activos_pvn';  

    protected $fillable = [
        "anio",
    "codigo_ue" ,
    "tipo_establecimiento" ,
    "desc_tipo_establecimiento" ,
    "establecimiento" ,
    "desc_establecimiento" ,
    "codigo_establecimiento_8" ,
    "unidad_organica" ,
    "desc_unidad_organica" ,
    "codigo_tipo_persona" ,
    "codigo_tipo_registro" ,
    "codigo_plaza" ,
    "codigo_plazaue" ,
    "estado" ,
    "tipo_documento" ,
    "numero_documento" ,
    "apellido_paterno" ,
    "apellido_materno" ,
    "nombres" ,
    "sexo" ,
    "desc_sexo" ,
    "fecha_nacimiento" ,
    "ingreso" ,
    "desc_ingreso" ,
    "fecha_ingreso" ,
    "regimen_laboral" ,
    "desc_regimen_laboral" ,
    "condicion" ,
    "desc_condicion" ,
    "grupo_ocupacional" ,
    "desc_grupo_ocupacional" ,
    "cargo_estructural" ,
    "desc_cargo_estructural" ,
    "horas" ,
    "cargo_funcional" ,
    "desc_cargo_funcional" ,
    "banco" ,
    "desc_banco" ,
    "tipo_cuenta" ,
    "desc_tipo_cuenta" ,
    "numero_cuenta" ,
    "cci" ,
    "fecha_afp" ,
    "afp" ,
    "desc_afp" ,
    "carnet_afp" ,
    "autogenerado" ,
    "fecha_alta" ,
    "fecha_estado" ,
    "fecha_inicio_vigencia_cas" ,
    "fecha_fin_vigencia_cas" ,
    "secuencia_funcional" ,
    "codigo_categoria_presupuestal" ,
    "desc_categoria_presupuestal" ,
    "codigo_producto" ,
    "desc_producto" ,
    "codigo_actividad" ,
    "desc_actividad" ,
    "codigo_funcion" ,
    "desc_funcion" ,
    "codigo_division_funcional" ,
    "desc_division_funcional" ,
    "codigo_grupo_funcional" ,
    "desc_grupo_funcional" ,
    "codigo_finalidad" ,
    "desc_finalidad" ,
    "codigo_departamento" ,
    "desc_departamento" ,
    "codigo_provincia" ,
    "desc_provincia" ,
    "codigo_distrito" ,
    "desc_distrito" ,
    "codigo_intervencion_estrategica" ,
    "desc_intervencion_estrategica" ,    
    /*"remprincipal_ro",
    "fuente" ,    
    "remprincipal_rdr" ,    
    "ds035_90_tr_bonfam" ,    
    "essalud" ,
    "bonifescolaridad" ,
    "ley_27735_gratificacion_por_fiestas_patrias" ,
    "ley_27735_gratificacion_por_navidad" ,
    "ley_30334_bonificacion_extraordinaria_julio" ,
    "ley_30334_bonificacion_extraordinaria_diciembre" ,*/
    ];
    
}