<?php namespace App\Http\Models;

use Illuminate\Database\Eloquent\Model;

class PresupuestoDB extends Model {
    public $incrementing = false;
    protected $table = 'presupuesto';     
    public $timestamps = false; 

    protected $fillable = [
        'ano_eje',
        'nivel_gob',  
        'pliego' ,
        'u_ejecutora',
        'sec_ejec',
        'programa_pptal',
        'tipo_prod_proy',
        'producto_proyecto',
        'tipo_act_obra_ac' ,
        'activ_obra_accinv',
        'funcion',
        'division_fn',
        'grupo_fn',
        'finalidad',
        'meta',
        'unidad_medida',
        'cant_meta_anual',
        'cant_meta_sem',
        'avan_fisico_anual',
        'avan_fisico_sem',
        'sec_func',
        'departamento_meta',
        'provincia_meta',
        'distrito_meta',
        'fuente_financ',
        'rubro', 
        'categoria_gasto',
        'tipo_transaccion',
        'generica',
        'subgenerica',
        'subgenerica_det',
        'especifica',
        'especifica_det',
        'tipo_recurso',
        'mto_pia',
        'mto_modificaciones',
        'mto_pim',
        'mto_certificado',
        'mto_compro_anual',
        'mto_at_comp_01',
        'mto_at_comp_02',
        'mto_at_comp_03',
        'mto_at_comp_04',
        'mto_at_comp_05',
        'mto_at_comp_06',
        'mto_at_comp_07',
        'mto_at_comp_08',
        'mto_at_comp_09',
        'mto_at_comp_10',
        'mto_at_comp_11',
        'mto_at_comp_12',
        'mto_devenga_01',
        'mto_devenga_02',
        'mto_devenga_03',
        'mto_devenga_04',
        'mto_devenga_05',
        'mto_devenga_06',
        'mto_devenga_07',
        'mto_devenga_08',
        'mto_devenga_09',
        'mto_devenga_10',
        'mto_devenga_11',
        'mto_devenga_12',
        'mto_girado_01',
        'mto_girado_02',
        'mto_girado_03',
        'mto_girado_04',
        'mto_girado_05',
        'mto_girado_06',
        'mto_girado_07',
        'mto_girado_08',
        'mto_girado_09',
        'mto_girado_10',
        'mto_girado_11',
        'mto_girado_12',
        'mto_pagado_01',
        'mto_pagado_02',
        'mto_pagado_03',
        'mto_pagado_04',
        'mto_pagado_05',
        'mto_pagado_06',
        'mto_pagado_07',
        'mto_pagado_08',
        'mto_pagado_09',
        'mto_pagado_10',
        'mto_pagado_11',
        'mto_pagado_12'
    ];

    protected $casts = [
        'mto_pia'=> 'float',
        'mto_modificaciones'=> 'float',
        'mto_pim'=> 'float',
        'mto_certificado'=> 'float',
        'mto_compro_anual'=> 'float',
        'mto_at_comp_01'=> 'float',
        'mto_at_comp_02'=> 'float',
        'mto_at_comp_03'=> 'float',
        'mto_at_comp_04'=> 'float',
        'mto_at_comp_05'=> 'float',
        'mto_at_comp_06'=> 'float',
        'mto_at_comp_07'=> 'float',
        'mto_at_comp_08'=> 'float',
        'mto_at_comp_09'=> 'float',
        'mto_at_comp_10'=> 'float',
        'mto_at_comp_11'=> 'float',
        'mto_at_comp_12'=> 'float',
        'mto_devenga_01'=> 'float',
        'mto_devenga_02'=> 'float',
        'mto_devenga_03'=> 'float',
        'mto_devenga_04'=> 'float',
        'mto_devenga_05'=> 'float',
        'mto_devenga_06'=> 'float',
        'mto_devenga_07'=> 'float',
        'mto_devenga_08'=> 'float',
        'mto_devenga_09'=> 'float',
        'mto_devenga_10'=> 'float',
        'mto_devenga_11'=> 'float',
        'mto_devenga_12'=> 'float',
        'mto_girado_01'=> 'float',
        'mto_girado_02'=> 'float',
        'mto_girado_03'=> 'float',
        'mto_girado_04'=> 'float',
        'mto_girado_05'=> 'float',
        'mto_girado_06'=> 'float',
        'mto_girado_07'=> 'float',
        'mto_girado_08'=> 'float',
        'mto_girado_09'=> 'float',
        'mto_girado_10'=> 'float',
        'mto_girado_11'=> 'float',
        'mto_girado_12'=> 'float',
        'mto_pagado_01'=> 'float',
        'mto_pagado_02'=> 'float',
        'mto_pagado_03'=> 'float',
        'mto_pagado_04'=> 'float',
        'mto_pagado_05'=> 'float',
        'mto_pagado_06'=> 'float',
        'mto_pagado_07'=> 'float',
        'mto_pagado_08'=> 'float',
        'mto_pagado_09'=> 'float',
        'mto_pagado_10'=> 'float',
        'mto_pagado_11'=> 'float',
        'mto_pagado_12'=> 'float'
    ];

}